### ISSUE TITLE
Whole pretrained embedding

### ISSUE THREAD

**Issue by yhcc** [ghaddarAbs/NER-with-LS#1]
Thanks to public your codes. And I rerun some of your experiments, I found that 'emb_matrix' in your released link was quite useful, do you have a link for the full embedding?

**Comment by ghaddarAbs** [comment]
Hi, 
Sorry for the late response... for some reason I haven't been notified by GitHub !!

The link to the full fasttext embeddings + code to generate LS representation are under the section **Generate LS embeddings** in README
