### ISSUE TITLE
Creating joblib files for a new dataset 

### ISSUE THREAD

**Issue by Nitya05** [ghaddarAbs/NER-with-LS#2]
I am trying to use your code for a new dataset, having a different set of entities. Since the entities are different from what CONLL-2003 and Ontonotes datasets provide, I need to train the Fasttext embeddings and the LS representations for my dataset.
Looking at the code, I assume that all these embeddings have been merged into one joblib file. (Correct me if I am wrong.)
What is the procedure of creating a joblib file for a new dataset?

Any help would be highly appreciated.

**Comment by ghaddarAbs** [comment]
Hi,
Sorry for the late response... for some reason I didn't get a notification from github !!

I am realizing a [new code](https://github.com/ghaddarAbs/NER-with-wikiDSCE) that improve over LS representation with contextualized embeddings. The code contains the full pipeline and all dependencies to preprocess _any file with .iob format_ to binary format and train a model. You don't need the full code, you just need to follow the same logic of the preprocess part.
