### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by ShaoQiBNU** [ghaddarAbs/NER-with-LS#4]
Hello, I run your code in windows as follows:
python model.py ontonotes

But I encounter the error:

![image](https://user-images.githubusercontent.com/37075909/66547736-7730d980-eb72-11e9-9007-277440980c46.png)

![image](https://user-images.githubusercontent.com/37075909/66547762-8748b900-eb72-11e9-8144-3968b7971087.png)

**Comment by ghaddarAbs** [comment]
Hi,

The code was tested on Linux, normally it should run on Windows without problems.
I don't have a GPU-powered Windows machine to test the code.
The bug occurs while training on conll or ontonotes?

**Comment by ShaoQiBNU** [comment]
I train the code in ontonotes and I think the problem is in the experiments.conf.  The char_filters should be 25 not 30. 
![image](https://user-images.githubusercontent.com/37075909/66726891-603e0000-ee6e-11e9-86e8-da27be100137.png)
And when I again train the code on Linux, it occurs another problem

![image](https://user-images.githubusercontent.com/37075909/66726934-a3986e80-ee6e-11e9-9426-04aa8e69832a.png)

**Comment by ghaddarAbs** [comment]
which version of tf are you using?
Also, please check CUDA version. I previously encounter problems using CNN with incompatible CUDA tf versions
